### PR TITLE
Throw error on macro name clash

### LINKED ISSUE #291: Compiler doesn't fail on "macro clash"
### Issue

When two macros with the same name are defined in file (or imported file), the compiler does not throw anything. It doesn't look desirable, because it's not even really clear which of the two macros will be used.

### Reproduction

Compile a file with two macros with the same name.

### PR DESCRIPTION
**Pull request by PraneshASP**
Resolves #291.

Tried running `cargo +nightly clippy --all --all-features -- -D warnings`,fails with some errors the `main` branch as well.

### CODE REVIEW

File: huff_parser/src/lib.rs [hunk 1]
```diff
@@ -185,6 +186,23 @@ impl Parser {
...
+    pub fn check_duplicate_macro(
+        &self,
+        contract: &mut Contract,
+        m: MacroDefinition,
+    ) -> Result<(), ParserError> {
+        if contract.macros.binary_search_by(|_macro| _macro.name.cmp(&m.name)).is_ok() {
+            return Err(ParserError {
+                kind: ParserErrorKind::DuplicateMacro(m.name),
+                hint: Some("MACRO names should be unique".to_string()),
+                spans: AstSpan(vec![self.spans[2].clone()]),
```
Comment (Maddiaa0) [inline huff_parser/src/lib.rs:199]: i assume this was meant to be m.spans rather than self.spans? 
Although i think the value being held will be the same

File: huff_parser/tests/macro.rs [hunk 2]
```diff
@@ -1232,3 +1232,69 @@ fn empty_test_with_multi_flag_decorator() {
...
+    #define macro MAIN() = takes(0) returns (0) {
+        0x00 calldataload 0xE0 shr
+        dup1 0x40c10f19 eq mints jumpi
+
+        mints:
+            MINT()
+    }
+    "#;
+
+    //let const_start = source.find("MINT()").unwrap_or(0);
```
Comment (Maddiaa0) [inline huff_parser/tests/macro.rs:1262]: are these meant to remain?

**Review by Maddiaa0 — COMMENTED** [review]
Looks great! I've re-based this onto stage and ran clippy --fix, Have some small comments!

File: huff_parser/tests/macro.rs (hunk 2 above)
Comment (PraneshASP) [reply huff_parser/tests/macro.rs]: Nope. Removed now 👍

File: huff_parser/src/lib.rs (hunk 1 above)
Comment (PraneshASP) [reply huff_parser/src/lib.rs:200]: rustc complains when I tried changing to m.spans..

File: huff_parser/src/lib.rs [hunk 3]
```diff
@@ -185,6 +186,23 @@ impl Parser {
...
     }
 
+    /// Checks if there is a duplicate macro name
+    pub fn check_duplicate_macro(
+        &self,
+        contract: &mut Contract,
+        m: MacroDefinition,
+    ) -> Result<(), ParserError> {
+        if contract.macros.binary_search_by(|_macro| _macro.name.cmp(&m.name)).is_ok() {
+            return Err(ParserError {
```
[the remark this answers is not in the document]
Comment (PraneshASP) [reply huff_parser/src/lib.rs]: added

**Review by Maddiaa0 — APPROVED** [review]
lgtm!
