### PR TITLE
fix: Invalid Parameter Types

### LINKED ISSUE #178: Incorrect usage of macro label not throwing a correct error
The incorrect usage of a macro label in the marco definition results in the compiler not throwing an error and instead using up all system memory and then exiting.

Contract to reproduce:
```
#define macro TEST(<value>) = takes(0) returns(0) {
    <value> 0x00 mstore
    0x20 0x00 return
}

#define macro MAIN() = takes(0) returns(0) {
    TEST(0x01)
}
```

Note the usage of definition of the macro `TEST` using `<value>` instead of `value`

### PR DESCRIPTION
**Pull request by abigger87**
## Overview

Previously, passing an unacceptable token as a parameter to a macro would cause the parser to loop indefinitely as it tried to find a closing parenthesis.

This pr introduces a check in parameter parsing that makes sure some sort of parameter was parsed (type or name), otherwise we have an invalid token.

Closes #178

### CODE REVIEW

File: huff_parser/src/lib.rs [hunk 1]
```diff
@@ -714,6 +716,8 @@ impl Parser {
             let mut arg = Argument::default();
             let mut arg_spans = vec![];
 
+            // tracing::debug!(target: "parser", "PARSING ARGUMENT TYPE");
```
Comment (clabby) [inline huff_parser/src/lib.rs:719]: nit- delete this

File: huff_parser/tests/breaking_param_invocation.rs [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+
+    // Parse tokens
+    let flattened_source = FullFileSource { source, file: None, spans: vec![] };
+    let lexer = Lexer::new(flattened_source);
+    let tokens = lexer.into_iter().map(|x| x.unwrap()).collect::<Vec<Token>>();
+    let mut parser = Parser::new(tokens, None);
+
+    // Should fail here
+    parser.parse().unwrap();
+}
```
Comment (clabby) [inline huff_parser/tests/breaking_param_invocation.rs:53]: nice!

File: huff_parser/src/lib.rs [hunk 3]
```diff
@@ -688,6 +688,8 @@ impl Parser {
     ) -> Result<Vec<Argument>, ParserError> {
         let mut args: Vec<Argument> = Vec::new();
         self.match_kind(TokenKind::OpenParen)?;
+        tracing::debug!(target: "parser", "PARSING ARGS...");
+        tracing::debug!(target: "parser", "PARSING ARGs: {:?}", self.current_token);
```
Comment (clabby) [inline huff_parser/src/lib.rs:692]: nit- delete first debug trace

**Review by clabby — CHANGES_REQUESTED** [review]
Looks great!

**Review by clabby — APPROVED** [review]
LGTM :rocket:
